---
- name: Create directory for Opensearch
  file:
    path: "{{ opensearch_dir }}"
    state: directory

- name: Set max_map_count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes

- name: Create docker-compose file for Opensearch
  template: 
    src: docker-compose.j2 
    dest: "{{ opensearch_dir }}/docker-compose.yml"

- name: Ensure docker network exist
  community.docker.docker_network:
    name: opensearch-net

- name: Apply opensearch docker-compose file
  become: true
  community.docker.docker_compose:
    project_src: "{{ opensearch_dir }}/"
    build: false
  register: output