Vagrant.configure("2") do |config|
    config.vm.define "logging" do |cfg|
        cfg.vm.box = "bento/ubuntu-20.04"
        cfg.vm.hostname = "logging"
        cfg.vm.network "private_network", ip: "192.168.40.40"
 
        cfg.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--memory", 2048]
            v.customize ["modifyvm", :id, "--cpus", "1"]  
            v.customize ["modifyvm", :id, "--name", "logging"]
        end
        
        # Basic config
        cfg.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "../Ansible/vagrant_basic.yml"
            ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
            ansible.raw_arguments  = "--vault-password-file=../Ansible/vaults/vault-pass.sh"
        end

        # Deploy Opensearch
        cfg.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "../Ansible/opensearch.yml"
            ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
            ansible.raw_arguments  = "--vault-password-file=../Ansible/vaults/vault-pass.sh"
        end

        # Deploy Fluentd
        cfg.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "../Ansible/fluentd.yml"
            ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
            ansible.raw_arguments  = "--vault-password-file=../Ansible/vaults/vault-pass.sh"
        end
    end
end
