- name: Permit login only with publickey.
  lineinfile:
      dest=/etc/ssh/sshd_config 
      regexp='^#?AuthenticationMethods' 
      line='AuthenticationMethods publickey'
  notify:
    - reload sshd

- name: Deny password authentication
  lineinfile:
      dest=/etc/ssh/sshd_config 
      regexp='^#?PasswordAuthentication' 
      line='PasswordAuthentication no'
  notify:
    - reload sshd

- name: Deny ChallengeResponseAuthentication
  lineinfile: 
      dest=/etc/ssh/sshd_config 
      regexp='^#?ChallengeResponseAuthentication' 
      line='ChallengeResponseAuthentication no'
  notify:
    - reload sshd

- name: Permit PubkeyAuthentication
  lineinfile: 
      dest=/etc/ssh/sshd_config 
      regexp='^#?PubkeyAuthentication' 
      line='PubkeyAuthentication yes' 
  notify:
    - reload sshd

- name: Deny root login    
  lineinfile: 
      dest=/etc/ssh/sshd_config 
      regexp='^PermitRootLogin' 
      line='PermitRootLogin No'
  notify:
    - reload sshd
