---
- name: basic config
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vaults/vaults.yml
  roles:
    - role: basic_config
    - role: geerlingguy.docker
      vars: 
        docker_users: ["admin"]
